# Generated by Django 6.0.4 on 2026-06-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerapplication",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
